use axum::{
    extract::{Path, Query, State},
    response::IntoResponse,
    Json,
};
use serde::Deserialize;

use crate::AppCtx;

/// Query parameters for GET /forecast/:asset_id.
#[derive(Deserialize)]
pub struct ForecastParams {
    pub timespan_s: Option<f64>,
}

/// Query parameters for GET /history/:asset_id.
#[derive(Deserialize)]
pub struct HistoryParams {
    pub timespan_s: Option<f64>,
}

/// GET /forecast/:asset_id — forward-looking TimeSeries for one asset (speckit 007).
/// Returns `{"samples": [{"ts": "...", "value": ...}], "interpolation": "..."}`.
pub async fn get_asset_forecast(
    State(ctx): State<AppCtx>,
    Path(asset_id): Path<String>,
    Query(params): Query<ForecastParams>,
) -> impl IntoResponse {
    use axum::http::StatusCode;
    use chrono::Duration;

    let timespan_s = params.timespan_s.unwrap_or(0.0);
    let timespan = Duration::milliseconds((timespan_s * 1000.0) as i64);
    let now = chrono::Utc::now();

    match ctx.sim_read.asset_forecast(&asset_id, timespan, now).await {
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({ "error": format!("unknown asset: {}", asset_id) })),
        )
            .into_response(),
        Some(series) => {
            let samples: Vec<serde_json::Value> = series
                .samples
                .iter()
                .map(|(ts, v)| serde_json::json!({ "ts": ts, "value": v }))
                .collect();
            Json(serde_json::json!({
                "samples": samples,
                "interpolation": series.interpolation,
            }))
            .into_response()
        }
    }
}

/// GET /capability/:asset_id — point-in-time feasible power range for one asset (Phase A).
/// Returns `{"max_import_kw": ..., "max_export_kw": ..., "min_import_kw": ...,
/// "min_export_kw": ..., "is_fixed": ..., "adjustability": ..., "key_features":
/// [{"label": ..., "value": ...}]}` plus the asset's
/// declared setpoint response, flattened (`power_steps_kw`, `step_rule`,
/// `snap_to_zero_below_kw`, `power_next_tick_kw` — R-81). BL-27: `adjustability`
/// is a static control-mode classification, not part of the live feasible range.
pub async fn get_asset_capability(
    State(ctx): State<AppCtx>,
    Path(asset_id): Path<String>,
) -> impl IntoResponse {
    use axum::http::StatusCode;

    match ctx.sim_read.asset_capability(&asset_id).await {
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({ "error": format!("unknown asset: {}", asset_id) })),
        )
            .into_response(),
        Some(view) => {
            let (cap, floor) = (view.capability, view.floor);
            // Serialized from the capability itself, so every field the asset
            // declares — including a future addition to its setpoint response
            // — reaches the UI without a second list to keep in step.
            let mut body = serde_json::json!({
                "min_import_kw": floor.min_import_kw,
                "min_export_kw": floor.min_export_kw,
                "is_fixed": view.is_fixed,
                // The asset's own display facts (peak power, capacity, typical load...):
                // generated by the asset, rendered by the UI without a per-kind branch.
                "key_features": view.key_features,
            });
            if let (Some(body), Some(cap)) = (
                body.as_object_mut(),
                serde_json::to_value(&cap).ok().and_then(|v| match v {
                    serde_json::Value::Object(map) => Some(map),
                    _ => None,
                }),
            ) {
                body.extend(cap);
            }
            Json(body).into_response()
        }
    }
}

/// GET /history/:asset_id — historical TimeSeries for one asset (speckit 007).
/// Returns `{"samples": [{"ts": "...", "value": ...}], "interpolation": "..."}`.
pub async fn get_asset_history(
    State(ctx): State<AppCtx>,
    Path(asset_id): Path<String>,
    Query(params): Query<HistoryParams>,
) -> impl IntoResponse {
    use axum::http::StatusCode;
    use chrono::Duration;

    let timespan_s = params.timespan_s.unwrap_or(0.0);
    let timespan = Duration::milliseconds((timespan_s * 1000.0) as i64);
    let now = chrono::Utc::now();

    match ctx.sim_read.asset_history(&asset_id, timespan, now).await {
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({ "error": format!("unknown asset: {}", asset_id) })),
        )
            .into_response(),
        Some(series) => {
            let samples: Vec<serde_json::Value> = series
                .samples
                .iter()
                .map(|(ts, v)| serde_json::json!({ "ts": ts, "value": v }))
                .collect();
            Json(serde_json::json!({
                "samples": samples,
                "interpolation": series.interpolation,
            }))
            .into_response()
        }
    }
}
