#!/usr/bin/env python3
"""Is the openspec tooling in this repo behind the published release?

The question this answers is not "what is installed on someone's laptop" — that
varies per machine and is nobody's business here. It is "what generated the
skills and commands committed to this repo", which every `SKILL.md` records in
its own frontmatter:

    metadata:
      generatedBy: "1.13.1"

That field is tracked in git, so it is the same answer for everyone, and it is
exactly what goes stale when a new openspec lands.

Exit codes: 0 = current (or ahead), 1 = an update is available, 2 = the check
itself could not run. The third is deliberately distinct: "the registry was
unreachable" must not read as "you are up to date".

Usage:
    python3 scripts/check_openspec_version.py [--json]
"""

import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

PACKAGE = "@fission-ai/openspec"
REGISTRY = "https://registry.npmjs.org/%40fission-ai%2Fopenspec/latest"
SKILLS_DIR = Path(__file__).resolve().parent.parent / ".claude" / "skills"
TIMEOUT_S = 20


def generated_by() -> "tuple[str, str] | None":
    """The version that generated our skills, and the file it came from.

    Reads every openspec skill rather than a hard-coded one, so removing or
    renaming a skill cannot silently turn this check into a no-op.
    """
    for skill in sorted(SKILLS_DIR.glob("openspec-*/SKILL.md")):
        match = re.search(
            r'^\s*generatedBy:\s*"?([0-9]+\.[0-9]+\.[0-9]+)"?\s*$',
            skill.read_text(encoding="utf-8"),
            re.MULTILINE,
        )
        if match:
            return match.group(1), skill.relative_to(SKILLS_DIR.parent.parent).as_posix()
    return None


def latest_published() -> str:
    with urllib.request.urlopen(REGISTRY, timeout=TIMEOUT_S) as response:
        return json.load(response)["version"]


def as_tuple(version: str) -> "tuple[int, ...]":
    return tuple(int(part) for part in version.split("."))


def main() -> int:
    as_json = "--json" in sys.argv

    found = generated_by()
    if found is None:
        print(
            "Could not find a generatedBy version in .claude/skills/openspec-*/SKILL.md —\n"
            "either the skills are gone or their frontmatter changed shape.",
            file=sys.stderr,
        )
        return 2
    current, source = found

    try:
        latest = latest_published()
    except (urllib.error.URLError, TimeoutError, KeyError, ValueError) as err:
        # Not "up to date" — unknown. Saying so is the whole point of exit 2.
        print(f"Could not reach the npm registry: {err}", file=sys.stderr)
        return 2

    behind = as_tuple(current) < as_tuple(latest)

    if as_json:
        print(json.dumps(
            {"package": PACKAGE, "current": current, "latest": latest,
             "behind": behind, "source": source},
            indent=2,
        ))
    elif behind:
        print(f"{PACKAGE}: {current} -> {latest} available (skills generated by {current})")
        print(f"  recorded in {source}")
        print("  to update: npm i -g @fission-ai/openspec@latest && npx openspec update")
        print("  then re-delete openspec-archive-change and openspec-sync-specs —")
        print("  `openspec update` reinstates them, and workflow rule 3 does not want them.")
    else:
        print(f"{PACKAGE}: {current} is current (latest published {latest})")

    return 1 if behind else 0


if __name__ == "__main__":
    sys.exit(main())
