#!/usr/bin/env bash
# wiki_callouts.sh — regenerate wiki/callouts.md, the index of all
# DRIFT / CONTRADICTION / OPEN QUESTION callouts across wiki content pages.
# The output file is auto-generated housekeeping: never edit it by hand.
# Wired into /wiki-sync and /wiki-lint; safe to run anytime.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

WIKI=wiki
OUT=$WIKI/callouts.md

{
    echo "# Callout Index"
    echo
    echo "> **Auto-generated** by \`scripts/wiki_callouts.sh\` — do not edit."
    echo "> Regenerated by /wiki-sync and /wiki-lint. First line of each callout shown;"
    echo "> follow the link for full context."
    echo

    for kind in "DRIFT" "CONTRADICTION" "OPEN QUESTION"; do
        echo "## $kind"
        echo
        matches=$(grep -rn "^> \*\*$kind\*\*" "$WIKI" --include='*.md' \
            --exclude='CLAUDE.md' --exclude='callouts.md' --exclude='index.md' \
            --exclude='log.md' --exclude='review.md' --exclude='purpose.md' || true)
        if [ -z "$matches" ]; then
            echo "_none_"
        else
            while IFS= read -r line; do
                file=${line%%:*}
                rest=${line#*:}
                lineno=${rest%%:*}
                text=${rest#*:}
                slug=$(basename "$file" .md)
                text=${text#> \*\*"$kind"\*\*}
                text=${text# }
                echo "- [[$slug]] (\`$file:$lineno\`) — $text …"
            done <<<"$matches"
        fi
        echo
    done
} >"$OUT"

count=$(grep -c '^- \[\[' "$OUT" || true)
echo "wrote $OUT ($count callouts)"
